#+title: README

* Background

I have been an auditor for years, starting with operational/financial audits and 
quickly transitioning to technology audits early in my career.

While performing technology audits, attestations, etc., you will find that it 
requires a lot of manual effort if you don't use the right tools to automate as 
much as possible.

This repository serves as my personal collection of audit tools that I want to 
save and re-use later.

** Scope

While I created the scripts and tools within this repository specifically for
the applications I use, I am working to include edge-cases and niche tools as I
can.

For now, refer to the tree below for application coverage.

#+begin_src shell
tree -I ".git*|venv"
#+end_src

#+begin_src text
├── CODEOWNERS
├── LICENSE
├── README.org
├── applications
│   ├── github
│   │   ├── README.org
│   │   ├── github_admins.py
│   │   ├── github_audit_log.py
│   │   ├── github_branch_protections.py
│   │   └── github_commits.py
│   └── gitlab
│       ├── README.org
│       ├── approvals.py
│       ├── branch_protections.py
│       ├── passwords.py
│       ├── provisioning.py
│       └── users.py
├── databases
│   ├── administrators
│   │   ├── mssql_admins.sql
│   │   ├── mysql_admins.sh
│   │   ├── mysql_admins.sql
│   │   ├── mysql_admins_alt.sql
│   │   ├── oracle_admins.sql
│   │   └── oracle_admins_alt.sql
│   └── passwords
│       └── sql
│           ├── data.csv
│           ├── get_data.sql
│           └── test.py
├── project_management
│   ├── alteryx
│   │   └── project_email_reminders.yxmd
│   ├── dash
│   │   └── app.py
│   └── powerbi
│       └── project_dashboard
│           ├── project_dashboard.pbix
│           └── project_data.xlsx
├── requirements.txt
└── sampling
    ├── README.org
    ├── sample-html.png
    ├── sample.html
    └── sample.py
#+end_src

* Development

** Python

For the Python scripts, use the following to activate a virtual environment for 
consistent packing:

#+begin_src sh
python3 -m venv venv
source ./venv/bin/activate
pip install PACKAGE_NAME
python3 ./PYTHON_SCRIPT.py
#+end_src
